### ISSUE TITLE
is this on google play?

### ISSUE THREAD

**Issue by albacoretuna** [lomza/screenlookcount#1]
Hi, is this released? I'd like to install.

**Comment by lomza** [comment]
Yes. https://play.google.com/store/apps/details?id=com.totemsoft.screenlookcount There is one issue though - the app can crush sometimes. I'll try to make an update soon :)

**Comment by albacoretuna** [comment]
Thanks :)

la 16. joulukuuta 2017 klo 12.45 Antonina <notifications@github.com>
kirjoitti:
